version: "3.9"
services:
  rffmpeg-worker:
    image: ghcr.io/nouun/rffmpeg-worker:latest
    environment:
      - SSH_USERS=kah:568:568
#      - SSH_ENABLE_ROOT=true # enable this if the above line is root:0:0
    ports:
      - "${WORKER_LAN_ONLY_IP:-}:22:22"
    volumes:
      - ./authorized_keys:/etc/authorized_keys/kah:Z
      - jellyfin-cache:/config/cache
      - jellyfin-transcodes:/config/transcodes
      - jellyfin-subtitles:/config/data/subtitles
      - media:/media:ro # no need for read-write
# add this for VAAPI support, for nvenc go to official jellyfin docs
#    devices:
#      - /dev/dri:/dev/dri
    restart: always
volumes:
  jellyfin-cache:
    driver: local
    driver_opts:
      type: nfs
      device: :/config/cache
      o: addr=$JELLYFIN_LAN_ONLY_IP,rw,nfsvers=4,sync,actimeo=1
  jellyfin-transcodes:
    driver: local
    driver_opts:
      type: nfs
      device: :/config/transcodes
      o: addr=$JELLYFIN_LAN_ONLY_IP,rw,nfsvers=4,sync,actimeo=1
  jellyfin-subtitles:
    driver: local
    driver_opts:
      type: nfs
      device: :/config/data/subtitles
      o: addr=$JELLYFIN_LAN_ONLY_IP,rw,nfsvers=4,sync,actimeo=1
  media:
    driver: local
    driver_opts:
      type: cifs
      device: //$MEDIA_USERNAME.your-storagebox.de/$MEDIA_USERNAME
      o: ro,addr=$MEDIA_USERNAME.your-storagebox.de,username=$MEDIA_USERNAME,password=$MEDIA_PASSWORD # no need for read-write
